# Here you can add groups with spawn reasons that will be allowed on WorldGuard regions
spawn-groups:
  default:
    mode: allow
    reasons:
      - CUSTOM
      - SPAWNER_EGG
  disallow_plugins:
    mode: disallow
    reasons:
      - CUSTOM